import type { PrivacyLevel, QuestionMeta, QuestionOption, QuestionType, SensitivityLevel } from "@/domain/types";

const GENERIC_OPTION_LABELS: Readonly<Record<string, string>> = {
  safe: "可以安全继续填写",
  unsafe: "现在不适合继续填写",
  unsure: "不太确定",
  none: "没有",
  some: "有一些",
  high: "风险很高",
  deferred: "暂时不判断",
  uncertain: "不确定",
  pressure_no_fear: "有人施压，但我目前没有明显害怕",
  pressure_or_fear: "有人施压，或我感到害怕",
  passing_but_safe: "闪过伤害自己/轻生的念头，但目前安全",
  unsafe_now: "我现在不安全，需要尽快求助",
  mild: "有轻微不适",
  severe: "有明显或紧急不适",
  confirmed: "已经确认",
  possible: "可能怀孕，但还没完全确认",
  unknown: "不清楚",
  test: "验孕试纸/验孕棒",
  blood: "验血",
  ultrasound: "B 超",
  clinician: "医生判断",
  not_yet: "还没有确认方式",
  other: "其他",
  under4: "4 周以内",
  week4to6: "4 到 6 周",
  week7to8: "7 到 8 周",
  week9to12: "9 到 12 周",
  over12: "超过 12 周",
  not_confirmed: "还没确认宫内",
  not_yet_confirmable: "目前时间太早，还不能确认",
  clear_or_persistent: "比较明显，或持续存在",
  severe_or_one_sided: "剧烈，或明显偏一侧",
  small: "少量",
  clear: "比较明显",
  heavy_or_with_pain_dizziness: "量大，或伴随疼痛/头晕",
  mild_one: "有一项轻微伴随症状",
  clear_one_or_more: "有一项或多项明显伴随症状",
  unclear_follow_up: "医生提过要继续观察，但我不太清楚原因",
  urgent_follow_up: "医生明确建议尽快复诊或处理",
  not_seen: "还没就诊",
  booked: "已经预约/建档",
  plan_to_book: "准备去预约",
  aware: "知道",
  unaware: "不知道",
  unsure_tell: "我不确定要不要告诉对方",
  lean_continue: "更倾向继续妊娠",
  lean_end: "更倾向终止妊娠",
  unclear: "还没有明确倾向",
  medical: "医疗与就诊",
  financial: "金钱支持",
  labor: "家务与照料分工",
  boundary: "帮我挡住外界压力",
  emotional: "情绪支持",
  long_term_parenting: "长期养育承诺",
  childcare: "已有孩子照料",
  contingency: "突发情况备用方案",
  one: "1 个",
  two: "2 个",
  three_plus: "3 个及以上",
  money: "金钱支持",
  appointment: "陪同就诊",
  recovery_care: "术后/产后照顾",
  household: "家务分担",
  housing: "住处支持",
  self: "主要是我自己",
  partner: "主要是伴侣",
  shared: "共同承担",
  grandparents: "长辈协助",
  service: "托育/家政/机构服务",
  age0to3: "0 到 3 岁",
  age3to6: "3 到 6 岁",
  primary: "小学阶段",
  secondary_plus: "初中及以上",
  autonomy: "自主选择",
  family: "家庭关系",
  relationship: "亲密关系",
  life: "人生节奏与计划",
  finance: "经济压力",
  health: "身心健康",
  willing: "愿意分享",
  maybe_with_selection: "可选部分分享",
  not_now: "现在不想分享",
  yes: "是",
  no: "否",
  arranged: "已经安排好",
  partly_arranged: "安排了一部分",
  prior_support: "以前有过专业支持",
  current_support: "现在正在接受支持",
  prefer_not_say: "不想回答",
  partly: "部分做到",
  partly_clear: "有一些想法，但还不够清楚",
  week1: "一周内",
  month1: "一个月内",
  year1: "一年内",
  year5: "五年内",
  facts: "先讲清事实",
  empathy: "先接住情绪",
  checklist: "给我一份清单",
  gradual: "一步一步来",
  space: "先给我一点空间",
  future: "未来安排",
  share: "可以共享给对方",
  do_not_share: "不要共享给对方",
  SD: "完全不符合",
  D: "不太符合",
  U: "不确定",
  A: "比较符合",
  SA: "非常符合",
};

const MODULE_LABELS: Readonly<Record<string, string>> = {
  safety: "安全与自主",
  medical: "医学状态",
  will: "个人意愿",
  mental: "情绪与心理",
  life: "人生与发展",
  partner: "伴侣关系",
  family: "家庭与支持",
  finance: "经济与政策",
  childcare: "已有孩子与照料",
  values: "价值排序",
  sharing: "补充说明与分享",
  "medical-deep": "就医安排补充",
  "mental-deep": "心理支持补充",
  "finance-deep": "经济情况补充",
  "partner-deep": "伴侣承诺补充",
  "life-deep": "人生规划补充",
  "care-deep": "照料安排补充",
  "values-deep": "价值澄清补充",
  "aftercare-deep": "后续照护补充",
  "safety-deep": "安全预案补充",
  "persona-deep": "互动风格校准",
  "partner-independent": "伴侣独立问卷",
};

const QUESTION_TITLES: Readonly<Record<string, string>> = {
  "Q-SAFE-FREE-ANSWER": "你现在是否处在可以安全、独立作答的环境里？",
  "Q-SAFE-PRIVACY-RISK": "如果你的设备、聊天记录或浏览记录被别人看到，会带来多大风险？",
  "Q-SAFE-COERCION": "最近是否有人在是否继续妊娠这件事上持续对你施压？",
  "Q-SAFE-SELF-HARM": "最近是否出现过伤害自己、轻生或觉得自己撑不下去的念头？",
  "Q-SAFE-URGENT-SYMPTOM": "你现在是否有需要优先排除的紧急身体不适？",
  "Q-MED-PREGNANCY-CONFIRMED": "这次怀孕目前确认到什么程度？",
  "Q-MED-CONFIRMATION-METHOD": "你通过哪些方式确认过怀孕情况？",
  "Q-MED-LAST-MENSTRUAL-PERIOD": "如果方便，填写最近一次月经开始的日期。",
  "Q-MED-GESTATION-ESTIMATE": "你估计当前大约在什么孕周阶段？",
  "Q-MED-INTRAUTERINE-CONFIRMED": "是否已经确认是宫内妊娠？",
  "Q-MED-ABDOMINAL-PAIN": "最近是否有腹痛？",
  "Q-MED-BLEEDING": "最近是否有出血？",
  "Q-MED-ASSOCIATED-SYMPTOMS": "是否伴随头晕、肩痛、发热或明显乏力等情况？",
  "Q-MED-CLINICIAN-RISK": "医生是否提示过需要尽快复诊、复查或进一步处理？",
  "Q-MED-CARE-PLAN": "你是否已经有下一步就医或随访安排？",
  "Q-WILL-SELF-VS-OTHERS": "在这件事上，我目前更能分辨自己真正的想法，而不是只回应别人的期待。",
  "Q-WILL-INFORMATION-BLOCK": "我觉得自己缺少关键信息，所以很难往前做决定。",
  "Q-WILL-VALUE-CONFLICT": "我内心有明显冲突，重要价值之间还没理顺。",
  "Q-WILL-DECISION-TIME": "我觉得决策时间压力很大，难以按照自己的节奏思考。",
  "Q-MH-MOOD-LOW": "这段时间，低落、难过或情绪掉下去的状态已经明显影响到我。",
  "Q-MH-WORRY-HIGH": "这段时间，焦虑、担心或脑子停不下来已经明显影响到我。",
  "Q-MH-FUNCTION-IMPACT": "情绪状态已经影响到我的睡眠、工作、学习或日常生活。",
  "Q-MH-SAFE-CONTACT": "如果我状态很差，我身边有一个可以安全联系的人。",
  "Q-MH-REGRET-WORRY": "我经常担心无论怎么选，之后都会非常后悔。",
  "Q-LIFE-PLAN-IMPORTANCE": "当前的人生计划、工作或学习安排，对我来说非常重要。",
  "Q-LIFE-CONTINUE-IMPACT": "如果继续妊娠，对我当前生活节奏和长期规划的影响会很大。",
  "Q-LIFE-END-IMPACT": "如果终止妊娠，对我接下来一段时间的身心恢复和安排影响会很大。",
  "Q-LIFE-FREEDOM-IMPORTANCE": "保有个人空间、行动自由和自主节奏，对我现在很重要。",
  "Q-LIFE-IDENTITY-PREPARED": "如果继续妊娠或成为照料者角色，我现在的准备度比较高。",
  "Q-LIFE-PARTNER-SUPPORT": "在现实生活安排上，我能获得稳定而持续的伴侣支持。",
  "Q-PARTNER-AWARE": "伴侣目前知道这次怀孕和你的处境吗？",
  "Q-PARTNER-DIRECTION": "伴侣目前大致是什么倾向？",
  "Q-PARTNER-RESPECT-AUTONOMY": "伴侣会尊重我的自主决定，而不是替我下结论。",
  "Q-PARTNER-SAFE-TO-SPEAK": "和伴侣谈这件事时，我基本能安全表达真实感受。",
  "Q-PARTNER-CONCRETE-COMMITMENT": "伴侣给出的支持承诺是具体、可执行的。",
  "Q-PARTNER-PAST-RELIABILITY": "从过往经验看，伴侣说过会做的事通常能做到。",
  "Q-PARTNER-CONTROL-RISK": "伴侣是否会用冷暴力、威胁、指责或控制来影响你的决定？",
  "Q-PARTNER-COMMITMENT-CATEGORIES": "如果伴侣愿意支持，哪些类型的支持最关键？",
  "Q-FAMILY-SUPPORT-SOURCES": "除了伴侣之外，你现在大概有多少可用支持来源？",
  "Q-FAMILY-SUPPORT-TYPES": "这些支持来源能提供哪些帮助？",
  "Q-FAMILY-SUPPORT-STABILITY": "这些支持在接下来一段时间里是稳定可依赖的。",
  "Q-FAMILY-BOUNDARY-PRESSURE": "家庭成员或重要他人会越界影响我的决定。",
  "Q-FAMILY-REFUSAL-CONSEQUENCE": "如果我不按他们期待去做，我会承担明显后果。",
  "Q-FAMILY-ACCEPT-SUPPORT": "即使意见不同，我也可以有边界地接受对我有帮助的支持。",
  "Q-FIN-INCOME-STABLE": "目前我的收入或家庭收入整体比较稳定。",
  "Q-FIN-SAVINGS-BUFFER": "我手头有一定缓冲，可以应对接下来几个月的波动。",
  "Q-FIN-FIXED-COST-PRESSURE": "固定支出压力已经比较大。",
  "Q-FIN-INSURANCE-KNOWN": "我大致知道相关医保或报销信息，不至于完全盲区。",
  "Q-FIN-CONTINUE-INCOME-IMPACT": "如果继续妊娠，对我的收入或工作安排影响会很明显。",
  "Q-FIN-POLICY-KNOWN": "我对本地可参考的政策和支持信息有基本了解。",
  "Q-FIN-CONTINUE-BUDGET": "如果继续妊娠，我对接下来的预算有一个现实方案。",
  "Q-FIN-END-BUDGET": "如果终止妊娠，我对医疗、恢复和后续安排成本有基本预估。",
  "Q-CHILD-COUNT": "你目前是否已经在照顾孩子？",
  "Q-CHILD-AGE-BANDS": "如果有，孩子大致处在什么年龄阶段？",
  "Q-CHILD-SPECIAL-NEEDS": "现有照料对象中，是否有人需要额外稳定照顾？",
  "Q-CHILD-PRIMARY-CARER": "现在谁承担主要照料责任？",
  "Q-CHILD-CONTINUE-CARE-IMPACT": "如果继续妊娠，现有照料安排会受到明显影响。",
  "Q-CHILD-END-RECOVERY-CARE": "如果终止妊娠，我恢复期间的照料安排是可行的。",
  "Q-VALUE-AUTONOMY-SAFETY": "能安全地按照自己的意愿做决定，对我非常重要。",
  "Q-VALUE-FAMILY-CONTINUITY": "家庭连续性和现有关系稳定，对我非常重要。",
  "Q-VALUE-SHARED-RESPONSIBILITY": "伴侣是否真正共同承担责任，对我非常重要。",
  "Q-VALUE-LIFE-RHYTHM": "保持当前生活节奏和发展方向，对我非常重要。",
  "Q-VALUE-CONTINUE-REGRET": "如果继续妊娠，我最担心的后悔感会很强。",
  "Q-VALUE-END-REGRET": "如果终止妊娠，我最担心的后悔感会很强。",
  "Q-VALUE-BOUNDARIES-KNOWN": "我对自己的底线和优先级已经有比较清楚的认识。",
  "Q-VALUE-PRIORITIES": "眼下你最想优先守住的几件事是什么？",
  "Q-VALUE-FUTURE-NOTE": "如果愿意，用一句话写下你希望一年后的自己回看今天时，最想感谢自己守住了什么。",
  "Q-FREE-OTHER-TEXT": "还有哪些你觉得重要、但前面还没覆盖到的情况？",
  "Q-FREE-PARTNER-UNDERSTAND-TEXT": "如果以后要和伴侣谈，你最希望对方先理解你哪一点？",
  "Q-SHARE-INTENT": "如果后续生成共同讨论页，你目前对分享范围的态度更接近哪一种？",
  "Q-DEEP-MED-NEXT-STEPS": "你是否已经知道接下来最需要确认的医学问题是什么？",
  "Q-DEEP-MED-APPOINTMENT-SUPPORT": "如果需要复诊或检查，陪同、请假或交通安排是否已有着落？",
  "Q-DEEP-MED-EMERGENCY-PLAN": "如果今晚或近期突然不适，你是否有明确的应对方案？",
  "Q-DEEP-MED-CLINICIAN-QUESTIONS": "如果要去看医生，你最想先问清楚什么？",
  "Q-DEEP-MH-SUPPORT-HISTORY": "过去或现在，你是否接触过心理/精神科/咨询等专业支持？",
  "Q-DEEP-MH-REST-PLAN": "接下来几天，你的休息和情绪缓冲安排得怎么样？",
  "Q-DEEP-MH-PROFESSIONAL-QUESTION": "如果和专业人士谈一次，你最想先说出的问题是什么？",
  "Q-DEEP-FIN-INCOME": "可选填：你每月大致可支配收入是多少？",
  "Q-DEEP-FIN-SAVINGS": "可选填：你目前大致可动用储蓄是多少？",
  "Q-DEEP-FIN-FIXED-COST": "可选填：你每月固定支出大约是多少？",
  "Q-DEEP-FIN-CHILDCARE-BUDGET": "可选填：如果涉及额外照料，你预估每月需增加多少预算？",
  "Q-DEEP-FIN-INCOME-GAP-MONTHS": "可选填：如果收入中断，你目前大约能撑几个月？",
  "Q-DEEP-PARTNER-COMMITMENT-EVIDENCE": "伴侣目前已经通过哪些实际行动证明支持，而不只是口头说法？",
  "Q-DEEP-PARTNER-COMMITMENT-TIMELINE": "你们是否已经聊过支持安排的时间线和触发点？",
  "Q-DEEP-PARTNER-COMMITMENT-TRUST": "你对这些承诺最终能落地的信任度如何？",
  "Q-DEEP-LIFE-PLANS": "接下来一年里，你最不想轻易放弃的计划是什么？",
  "Q-DEEP-LIFE-REPLACEABILITY": "这些计划里，哪些是可以延后，哪些一旦错过就很难补回？",
  "Q-DEEP-LIFE-PARTNER-TRADEOFF": "如果为了支持你，伴侣也需要调整自己的计划，你们是否谈过这种取舍？",
  "Q-DEEP-CARE-RECOVERY": "如果你需要恢复或休息，白天照料能否安排出来？",
  "Q-DEEP-CARE-NIGHT": "如果夜间需要帮助，是否有人能顶上？",
  "Q-DEEP-CARE-BACKUP": "原计划失效时，是否有第二套备用安排？",
  "Q-DEEP-VALUE-FUTURE-FERTILITY": "关于未来生育、关系和身体感受，你现在的在意点清楚吗？",
  "Q-DEEP-VALUE-REVIEW": "如果以后回看这次决定，你最想在什么时间点提醒自己再复盘一次？",
  "Q-DEEP-AFTER-CONTINUE-PLAN": "如果继续妊娠，你最希望接下来两周先落实哪三件事？",
  "Q-DEEP-AFTER-END-PLAN": "如果终止妊娠，你最希望接下来两周先落实哪三件事？",
  "Q-DEEP-SAFETY-DELETE-ABILITY": "如果需要，你是否能安全删除记录、退出页面或换设备？",
  "Q-DEEP-SAFETY-TRUSTED-CONTACT": "如果情况不好，你是否有一个可信的人能帮你兜底？",
  "Q-DEEP-SAFETY-SHARING-AVOID": "如果你不想共享某些内容，是否有办法避免被迫展示给别人？",
  "Q-ROLE-FACT-CHECK": "遇到重大决定时，我会先核对事实和边界条件。",
  "Q-ROLE-PLAN-LIST": "把事情列成清单、拆成步骤，会让我更安心。",
  "Q-ROLE-CHANGE-SENSITIVITY": "只要环境里有细微变化，我通常会很快察觉。",
  "Q-ROLE-NEED-SUPPORT": "当压力很高时，我会明确感到自己需要被支持。",
  "Q-ROLE-EMOTION-EXPRESSION": "我比较能把自己的情绪感受说出来。",
  "Q-ROLE-NEED-SPACE": "当事情太满时，我需要先拉开一点距离再想。",
  "Q-ROLE-SHARED-PARTICIPATION": "我会希望重要的人和我一起参与讨论，而不是旁观。",
  "Q-ROLE-COMMITMENT-EVIDENCE": "我更相信被兑现过的行动，而不是口头承诺。",
  "Q-ROLE-BOUNDARY-NEED": "在复杂关系里，我会更看重边界是否清楚。",
  "Q-ROLE-LONG-TERM-REVIEW": "做决定时，我会自然去想一年后、几年后的影响。",
  "Q-ROLE-LIFE-CONTINUITY": "我会很在意当前生活秩序是否还能接得住变化。",
  "Q-ROLE-RESOURCE-CAPACITY": "我会先盘点现实资源，再决定自己能扛到哪里。",
  "Q-PARTNER-SUPPORT-PREFERENCE": "如果由伴侣来支持你，你更希望对方怎么做？",
  "Q-PARTNER-OFFER-CATEGORIES": "如果伴侣愿意帮忙，哪些支持最值得优先承诺？",
  "Q-PARTNER-DISCUSS-TOPICS": "接下来你们最需要先谈清楚哪些主题？",
  "Q-PARTNER-SHARE-SUMMARY": "你愿意把伴侣侧问卷摘要共享给用户讨论页吗？",
};

function option(code: string): QuestionOption {
  return { code, label: GENERIC_OPTION_LABELS[code] ?? code };
}

export function options(codes: readonly string[]): readonly QuestionOption[] {
  return codes.map(option);
}

export function getModuleLabel(moduleId: string): string {
  return MODULE_LABELS[moduleId] ?? moduleId;
}

export interface QuestionSeed {
  answerKey: string;
  moduleId: string;
  questionType: QuestionType;
  optionCodes?: readonly string[];
  required?: boolean;
  audience?: "user" | "partner";
  phase?: "core" | "deepDive" | "partnerSupport" | "personaAssessment";
  privacy?: PrivacyLevel;
  sensitivity?: SensitivityLevel;
  sourceId?: string;
  visibleWhen?: readonly string[];
}

export function defineQuestion(seed: QuestionSeed): QuestionMeta {
  return {
    id: seed.answerKey,
    answerKey: seed.answerKey,
    audience: seed.audience ?? "user",
    phase: seed.phase ?? "core",
    moduleId: seed.moduleId,
    questionType: seed.questionType,
    title: QUESTION_TITLES[seed.answerKey] ?? seed.answerKey,
    options: seed.optionCodes ? options(seed.optionCodes) : undefined,
    required: seed.required ?? false,
    privacy: seed.privacy ?? "private",
    sensitivity: seed.sensitivity ?? "freeText",
    sourceId: seed.sourceId,
    visibleWhen: seed.visibleWhen,
  };
}
