import { defineQuestion } from "./_shared";

export const DEEP_DIVE_MODULE_IDS = [
  "medical-deep",
  "mental-deep",
  "finance-deep",
  "partner-deep",
  "life-deep",
  "care-deep",
  "values-deep",
  "aftercare-deep",
  "safety-deep",
  "persona-deep",
  "partner-independent",
] as const;

export const DEEP_DIVE_QUESTIONS = [
  defineQuestion({ answerKey: "Q-DEEP-MED-NEXT-STEPS", moduleId: "medical-deep", questionType: "singleSelect", optionCodes: ["yes", "no", "unknown"], phase: "deepDive", sourceId: "SRC-NHC-FULL-CARE" }),
  defineQuestion({ answerKey: "Q-DEEP-MED-APPOINTMENT-SUPPORT", moduleId: "medical-deep", questionType: "singleSelect", optionCodes: ["arranged", "partly_arranged", "none", "unknown"], phase: "deepDive", sourceId: "SRC-NHC-MATERNAL-CARE" }),
  defineQuestion({ answerKey: "Q-DEEP-MED-EMERGENCY-PLAN", moduleId: "medical-deep", questionType: "singleSelect", optionCodes: ["arranged", "partly_arranged", "none", "unknown"], phase: "deepDive", sourceId: "SRC-CDC-UMWS" }),
  defineQuestion({ answerKey: "Q-DEEP-MED-CLINICIAN-QUESTIONS", moduleId: "medical-deep", questionType: "freeText", phase: "deepDive", sourceId: "SPEC-QUESTIONNAIRE" }),
  defineQuestion({ answerKey: "Q-DEEP-MH-SUPPORT-HISTORY", moduleId: "mental-deep", questionType: "singleSelect", optionCodes: ["none", "prior_support", "current_support", "prefer_not_say"], phase: "deepDive", sourceId: "SRC-NICE-CG192" }),
  defineQuestion({ answerKey: "Q-DEEP-MH-REST-PLAN", moduleId: "mental-deep", questionType: "singleSelect", optionCodes: ["arranged", "partly_arranged", "none", "unknown"], phase: "deepDive", sourceId: "SRC-ACOG-PMH-SCREENING" }),
  defineQuestion({ answerKey: "Q-DEEP-MH-PROFESSIONAL-QUESTION", moduleId: "mental-deep", questionType: "freeText", phase: "deepDive", sourceId: "SRC-NICE-CG192" }),
  defineQuestion({ answerKey: "Q-DEEP-FIN-INCOME", moduleId: "finance-deep", questionType: "currency", phase: "deepDive", sourceId: "SPEC-QUESTIONNAIRE" }),
  defineQuestion({ answerKey: "Q-DEEP-FIN-SAVINGS", moduleId: "finance-deep", questionType: "currency", phase: "deepDive", sourceId: "SPEC-QUESTIONNAIRE" }),
  defineQuestion({ answerKey: "Q-DEEP-FIN-FIXED-COST", moduleId: "finance-deep", questionType: "currency", phase: "deepDive", sourceId: "SPEC-QUESTIONNAIRE" }),
  defineQuestion({ answerKey: "Q-DEEP-FIN-CHILDCARE-BUDGET", moduleId: "finance-deep", questionType: "currency", phase: "deepDive", sourceId: "SPEC-QUESTIONNAIRE" }),
  defineQuestion({ answerKey: "Q-DEEP-FIN-INCOME-GAP-MONTHS", moduleId: "finance-deep", questionType: "currency", phase: "deepDive", sourceId: "SPEC-QUESTIONNAIRE" }),
  defineQuestion({ answerKey: "Q-DEEP-PARTNER-COMMITMENT-EVIDENCE", moduleId: "partner-deep", questionType: "multiSelect", optionCodes: ["medical", "financial", "labor", "boundary", "emotional", "long_term_parenting", "childcare", "contingency", "none"], phase: "deepDive", sourceId: "SPEC-QUESTIONNAIRE" }),
  defineQuestion({ answerKey: "Q-DEEP-PARTNER-COMMITMENT-TIMELINE", moduleId: "partner-deep", questionType: "singleSelect", optionCodes: ["yes", "partly", "no", "unknown"], phase: "deepDive", sourceId: "SPEC-QUESTIONNAIRE" }),
  defineQuestion({ answerKey: "Q-DEEP-PARTNER-COMMITMENT-TRUST", moduleId: "partner-deep", questionType: "scale", optionCodes: ["SD", "D", "U", "A", "SA"], phase: "deepDive", sourceId: "SPEC-QUESTIONNAIRE" }),
  defineQuestion({ answerKey: "Q-DEEP-LIFE-PLANS", moduleId: "life-deep", questionType: "freeText", phase: "deepDive", sourceId: "SPEC-QUESTIONNAIRE" }),
  defineQuestion({ answerKey: "Q-DEEP-LIFE-REPLACEABILITY", moduleId: "life-deep", questionType: "freeText", phase: "deepDive", sourceId: "SPEC-QUESTIONNAIRE" }),
  defineQuestion({ answerKey: "Q-DEEP-LIFE-PARTNER-TRADEOFF", moduleId: "life-deep", questionType: "singleSelect", optionCodes: ["yes", "partly", "no", "unknown"], phase: "deepDive", sourceId: "SPEC-QUESTIONNAIRE" }),
  defineQuestion({ answerKey: "Q-DEEP-CARE-RECOVERY", moduleId: "care-deep", questionType: "singleSelect", optionCodes: ["arranged", "partly_arranged", "none", "unknown"], phase: "deepDive", sourceId: "SPEC-QUESTIONNAIRE" }),
  defineQuestion({ answerKey: "Q-DEEP-CARE-NIGHT", moduleId: "care-deep", questionType: "singleSelect", optionCodes: ["arranged", "partly_arranged", "none", "unknown"], phase: "deepDive", sourceId: "SPEC-QUESTIONNAIRE" }),
  defineQuestion({ answerKey: "Q-DEEP-CARE-BACKUP", moduleId: "care-deep", questionType: "singleSelect", optionCodes: ["arranged", "partly_arranged", "none", "unknown"], phase: "deepDive", sourceId: "SPEC-QUESTIONNAIRE" }),
  defineQuestion({ answerKey: "Q-DEEP-VALUE-FUTURE-FERTILITY", moduleId: "values-deep", questionType: "singleSelect", optionCodes: ["clear", "partly_clear", "unclear", "deferred"], phase: "deepDive", sourceId: "SRC-OTTAWA-ODSF" }),
  defineQuestion({ answerKey: "Q-DEEP-VALUE-REVIEW", moduleId: "values-deep", questionType: "multiSelect", optionCodes: ["week1", "month1", "year1", "year5"], phase: "deepDive", sourceId: "SRC-OTTAWA-ODSF" }),
  defineQuestion({ answerKey: "Q-DEEP-AFTER-CONTINUE-PLAN", moduleId: "aftercare-deep", questionType: "freeText", phase: "deepDive", sourceId: "SPEC-QUESTIONNAIRE" }),
  defineQuestion({ answerKey: "Q-DEEP-AFTER-END-PLAN", moduleId: "aftercare-deep", questionType: "freeText", phase: "deepDive", sourceId: "SPEC-QUESTIONNAIRE" }),
  defineQuestion({ answerKey: "Q-DEEP-SAFETY-DELETE-ABILITY", moduleId: "safety-deep", questionType: "singleSelect", optionCodes: ["yes", "no", "unknown"], phase: "deepDive", visibleWhen: ["Q-SAFE-PRIVACY-RISK!=none"], sourceId: "SRC-ACOG-IPV" }),
  defineQuestion({ answerKey: "Q-DEEP-SAFETY-TRUSTED-CONTACT", moduleId: "safety-deep", questionType: "singleSelect", optionCodes: ["yes", "no", "unknown"], phase: "deepDive", visibleWhen: ["Q-SAFE-PRIVACY-RISK!=none"], sourceId: "SRC-ACOG-IPV" }),
  defineQuestion({ answerKey: "Q-DEEP-SAFETY-SHARING-AVOID", moduleId: "safety-deep", questionType: "singleSelect", optionCodes: ["yes", "no", "unknown"], phase: "deepDive", visibleWhen: ["Q-SAFE-COERCION in {pressure_no_fear,pressure_or_fear}"], sourceId: "SRC-ACOG-REPRO-COERCION" }),
  defineQuestion({ answerKey: "Q-ROLE-FACT-CHECK", moduleId: "persona-deep", questionType: "scale", optionCodes: ["SD", "D", "U", "A", "SA"], phase: "personaAssessment", sourceId: "SPEC-PERSONAS" }),
  defineQuestion({ answerKey: "Q-ROLE-PLAN-LIST", moduleId: "persona-deep", questionType: "scale", optionCodes: ["SD", "D", "U", "A", "SA"], phase: "personaAssessment", sourceId: "SPEC-PERSONAS" }),
  defineQuestion({ answerKey: "Q-ROLE-CHANGE-SENSITIVITY", moduleId: "persona-deep", questionType: "scale", optionCodes: ["SD", "D", "U", "A", "SA"], phase: "personaAssessment", sourceId: "SPEC-PERSONAS" }),
  defineQuestion({ answerKey: "Q-ROLE-NEED-SUPPORT", moduleId: "persona-deep", questionType: "scale", optionCodes: ["SD", "D", "U", "A", "SA"], phase: "personaAssessment", sourceId: "SPEC-PERSONAS" }),
  defineQuestion({ answerKey: "Q-ROLE-EMOTION-EXPRESSION", moduleId: "persona-deep", questionType: "scale", optionCodes: ["SD", "D", "U", "A", "SA"], phase: "personaAssessment", sourceId: "SPEC-PERSONAS" }),
  defineQuestion({ answerKey: "Q-ROLE-NEED-SPACE", moduleId: "persona-deep", questionType: "scale", optionCodes: ["SD", "D", "U", "A", "SA"], phase: "personaAssessment", sourceId: "SPEC-PERSONAS" }),
  defineQuestion({ answerKey: "Q-ROLE-SHARED-PARTICIPATION", moduleId: "persona-deep", questionType: "scale", optionCodes: ["SD", "D", "U", "A", "SA"], phase: "personaAssessment", sourceId: "SPEC-PERSONAS" }),
  defineQuestion({ answerKey: "Q-ROLE-COMMITMENT-EVIDENCE", moduleId: "persona-deep", questionType: "scale", optionCodes: ["SD", "D", "U", "A", "SA"], phase: "personaAssessment", sourceId: "SPEC-PERSONAS" }),
  defineQuestion({ answerKey: "Q-ROLE-BOUNDARY-NEED", moduleId: "persona-deep", questionType: "scale", optionCodes: ["SD", "D", "U", "A", "SA"], phase: "personaAssessment", sourceId: "SPEC-PERSONAS" }),
  defineQuestion({ answerKey: "Q-ROLE-LONG-TERM-REVIEW", moduleId: "persona-deep", questionType: "scale", optionCodes: ["SD", "D", "U", "A", "SA"], phase: "personaAssessment", sourceId: "SPEC-PERSONAS" }),
  defineQuestion({ answerKey: "Q-ROLE-LIFE-CONTINUITY", moduleId: "persona-deep", questionType: "scale", optionCodes: ["SD", "D", "U", "A", "SA"], phase: "personaAssessment", sourceId: "SPEC-PERSONAS" }),
  defineQuestion({ answerKey: "Q-ROLE-RESOURCE-CAPACITY", moduleId: "persona-deep", questionType: "scale", optionCodes: ["SD", "D", "U", "A", "SA"], phase: "personaAssessment", sourceId: "SPEC-PERSONAS" }),
  defineQuestion({ answerKey: "Q-PARTNER-SUPPORT-PREFERENCE", moduleId: "partner-independent", questionType: "multiSelect", optionCodes: ["facts", "empathy", "checklist", "gradual", "space"], audience: "partner", phase: "partnerSupport", sourceId: "SPEC-QUESTIONNAIRE" }),
  defineQuestion({ answerKey: "Q-PARTNER-OFFER-CATEGORIES", moduleId: "partner-independent", questionType: "multiSelect", optionCodes: ["medical", "financial", "labor", "boundary", "emotional", "long_term_parenting", "childcare", "contingency"], audience: "partner", phase: "partnerSupport", sourceId: "SPEC-QUESTIONNAIRE" }),
  defineQuestion({ answerKey: "Q-PARTNER-DISCUSS-TOPICS", moduleId: "partner-independent", questionType: "multiSelect", optionCodes: ["medical", "finance", "labor", "boundary", "emotional", "future", "childcare"], audience: "partner", phase: "partnerSupport", sourceId: "SPEC-QUESTIONNAIRE" }),
  defineQuestion({ answerKey: "Q-PARTNER-SHARE-SUMMARY", moduleId: "partner-independent", questionType: "singleSelect", optionCodes: ["share", "do_not_share"], audience: "partner", phase: "partnerSupport", sourceId: "SPEC-REPORT-SHARING" }),
] as const;
