import { defineQuestion } from "./_shared";

export const MEDICAL_QUESTIONS = [
  defineQuestion({
    answerKey: "Q-MED-PREGNANCY-CONFIRMED",
    moduleId: "medical",
    questionType: "singleSelect",
    optionCodes: ["confirmed", "possible", "unknown"],
    required: true,
    sensitivity: "medical",
    sourceId: "SPEC-QUESTIONNAIRE",
  }),
  defineQuestion({
    answerKey: "Q-MED-CONFIRMATION-METHOD",
    moduleId: "medical",
    questionType: "multiSelect",
    optionCodes: ["test", "blood", "ultrasound", "clinician", "not_yet", "other"],
    sensitivity: "medical",
    sourceId: "SPEC-QUESTIONNAIRE",
  }),
  defineQuestion({
    answerKey: "Q-MED-LAST-MENSTRUAL-PERIOD",
    moduleId: "medical",
    questionType: "date",
    sensitivity: "medical",
    sourceId: "SPEC-QUESTIONNAIRE",
  }),
  defineQuestion({
    answerKey: "Q-MED-GESTATION-ESTIMATE",
    moduleId: "medical",
    questionType: "singleSelect",
    optionCodes: ["under4", "week4to6", "week7to8", "week9to12", "over12", "unknown"],
    sensitivity: "medical",
    sourceId: "SPEC-QUESTIONNAIRE",
  }),
  defineQuestion({
    answerKey: "Q-MED-INTRAUTERINE-CONFIRMED",
    moduleId: "medical",
    questionType: "singleSelect",
    optionCodes: ["confirmed", "not_confirmed", "not_yet_confirmable", "unknown"],
    required: true,
    sensitivity: "medical",
    sourceId: "SPEC-QUESTIONNAIRE",
  }),
  defineQuestion({
    answerKey: "Q-MED-ABDOMINAL-PAIN",
    moduleId: "medical",
    questionType: "singleSelect",
    optionCodes: ["none", "mild", "clear_or_persistent", "severe_or_one_sided"],
    required: true,
    sensitivity: "medical",
    sourceId: "SRC-NICE-NG126",
  }),
  defineQuestion({
    answerKey: "Q-MED-BLEEDING",
    moduleId: "medical",
    questionType: "singleSelect",
    optionCodes: ["none", "small", "clear", "heavy_or_with_pain_dizziness"],
    required: true,
    sensitivity: "medical",
    sourceId: "SRC-NICE-NG126",
  }),
  defineQuestion({
    answerKey: "Q-MED-ASSOCIATED-SYMPTOMS",
    moduleId: "medical",
    questionType: "singleSelect",
    optionCodes: ["none", "mild_one", "clear_one_or_more"],
    required: true,
    sensitivity: "medical",
    sourceId: "SRC-NHS-ECTOPIC",
  }),
  defineQuestion({
    answerKey: "Q-MED-CLINICIAN-RISK",
    moduleId: "medical",
    questionType: "singleSelect",
    optionCodes: ["none", "unclear_follow_up", "urgent_follow_up", "not_seen"],
    sensitivity: "medical",
    sourceId: "SRC-NHC-MATERNAL-CARE",
  }),
  defineQuestion({
    answerKey: "Q-MED-CARE-PLAN",
    moduleId: "medical",
    questionType: "singleSelect",
    optionCodes: ["booked", "plan_to_book", "none", "unknown"],
    sensitivity: "medical",
    sourceId: "SRC-NHC-FULL-CARE",
  }),
] as const;
